blank_issues_enabled: false

contact_links:
  - name: â“ Question
    url: https://github.com/projectsyn/k8s-service-ca-controller/discussions
     about: Ask or discuss with us, we're happy to help ğŸ™‹
