site:
  title: Kubernetes Service CA controller
  start_page: k8s-service-ca-controller::index.adoc
  url: https://syn.tools/k8s-service-ca-controller
content:
  sources:
    - url: ../antora
      branches:
        - HEAD
        - docs/v*
      start_path: docs
ui:
  bundle:
    url: https://github.com/projectsyn/antora-ui-default/releases/download/2.1.0/ui-bundle.zip
    snapshot: true
output:
  dir: .public/
  clean: true
